---
- name: Manage GNS3 devices
  hosts: R1, R2, S1, S2
  gather_facts: false
  connection: network_cli

  tasks:
    - name: enable ospf
      ios_config:
        parents: router ospf 1
        lines:
          - network 0.0.0.0 255.255.255.255 area 0

      register: print_output

    -  debug: var=print_output

